### ISSUE TITLE
Showing reference terms

### ISSUE THREAD

**Issue by mehrlander** [guyabel/tidycat#3]
This is a neat feature- does it deserve more attention?  As one thing your second header has "Additional columns on broom::tidy() for categorical parameter estimates."  This should maybe find a way to mention "columns and rows"?

I was experimenting then with no-intercept models to see how they would treat the reference category.  It seems you can make a no intercept version of lm() by including either "+ 0" or "- 1" as an independent variable term: [see link](https://stats.stackexchange.com/questions/143155/doing-multiple-regression-without-intercept-in-r-without-changing-data-dimensio).  Tidymodels seems to have other methods, described [here](https://recipes.tidymodels.org/articles/Dummies.html).  I'm not sure there's anything here for tidycat to address, but perhaps others will also have questions about how this feature fits into other methods for examining the reference category.

**Comment by guyabel** [comment]
good idea... i added an extra section to highlight the additional rows so that hopefully it is clearer to the reader.

i am a bit afraid to think about reference coding schemes and how they might work/not work with tidycat... going to leave it for the time being,..  i guess  99% of people do not tinker with contrasts in R.
